# NOTE: Do not edit, file was generated by jhconvert

Name: sugar-datastore
Version: 0.85.1
Release: %mkrel 1
Summary: Datastore service for Sugar
License: GPL
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/sucrose/glucose/sugar-datastore/sugar-datastore-0.85.1.tar.bz2

Requires: python-dbus  
Requires: python  
Requires: python-cjson  
Requires: sugar-base >= 0.85.2
Requires: xapian-bindings-python  

BuildRequires: libpython-devel  

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)


%description
This package contains a simple log like datastore able to connect with multiple
backends. The datastore supports connecting and disconnecting from backends
on the fly to help the support the limit space/memory characteristics and
the fact that network services may become unavailable at times.

%prep
%setup -q -n sugar-datastore-0.85.1


%build
%define __libtoolize true
%configure
make

%install
rm -rf %{buildroot}
make DESTDIR=%{buildroot} install


%clean
rm -rf %{buildroot}

%files 
%defattr(-,root,root,-)
%dir %{_datadir}/dbus-1
%dir %{_datadir}/dbus-1/services
%{_bindir}/*
%{_datadir}/dbus*/services/*
%{python_sitelib}/*
%doc LICENSE.GPL README.txt

