# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details
%define _disable_ld_no_undefined 1

Name:		sugar-datastore
Version:	0.88.0
Release:	3
Summary:	Datastore service for Sugar
License:	GPL
Group:		Graphical desktop/Other
Url:		http://sugarlabs.org/

Source0:	http://download.sugarlabs.org/sources/sucrose/glucose/sugar-datastore/sugar-datastore-0.88.0.tar.bz2

Requires:	python-dbus  
Requires:	python  
Requires:	python-cjson  
Requires:	sugar-base >= 0.88.0
Requires:	xapian-bindings-python  

BuildRequires:	python-devel  


%description
This package contains a simple log like datastore able to connect with multiple
backends. The datastore supports connecting and disconnecting from backends
on the fly to help the support the limit space/memory characteristics and
the fact that network services may become unavailable at times.

%prep
%setup -q -n sugar-datastore-0.88.0


%build
%define __libtoolize true
%configure
%make

%install
%makeinstall_std


%files 
%dir %{_datadir}/dbus-1
%dir %{_datadir}/dbus-1/services
%{_bindir}/*
%{_datadir}/dbus*/services/*
%{python_sitelib}/*
%doc AUTHORS COPYING NEWS README

